name: holowinsky
favicon: null
layout_spectrum: 0.5198927568271756
typography_spectrum: 0.3676080033183098
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.040393696166574955
  lightness: 0.009851323440670967
  saturation: 0.5041731579694897
  rhythmicContrast: 0.2155108591541648
purpose: []
